
################################################################################
GET {{hostName}}courses


################################################################################

GET {{hostName}}courses/1

################################################################################

POST {{hostName}}courses
Content-Type: application/json

################################################################################

PUT {{hostName}}courses/1

################################################################################

PATCH {{hostName}}courses/1

################################################################################

DELETE {{hostName}}courses/1

################################################################################
