
################################################################################
GET {{baseUrl}}courses


################################################################################

GET {{baseUrl}}courses/1

################################################################################

POST {{baseUrl}}courses
Content-Type: application/json

################################################################################

PUT {{baseUrl}}courses/1

################################################################################

PATCH {{baseUrl}}courses/1

################################################################################

DELETE {{baseUrl}}courses/1

################################################################################
