@cpf = 70023173158

GET {{hostName}}/balance
Accept: application/json
cpf: {{cpf}}

###
DELETE {{hostName}}/account
Accept: application/json
cpf: {{cpf}}

###
GET {{hostName}}/account
Accept: application/json
cpf: {{cpf}}

###
PUT {{hostName}}/account
Content-Type: application/json
cpf: {{cpf}}

{
  "name": "vitor"
}

###
GET {{hostName}}/statement/date?date=2021-11-28
Accept: application/json
cpf: {{cpf}}

###
POST {{hostName}}/withdraw
Content-Type: application/json
cpf: {{cpf}}

{
  "amount": 100
}

###
POST {{hostName}}/deposit
Content-Type: application/json
cpf: {{cpf}}

{
  "amount": 3500.00,
  "description": "Transferencia Ignite"
}

###
GET {{hostName}}/statement
Content-Type: application/json
cpf: {{cpf}}

###
POST {{hostName}}/account
Content-Type: application/json

{
  "cpf": {{cpf}},
  "name": "Fulano de Tal"
}


